### ISSUE TITLE
Problem loading QgsProjectionSelectionWidget

### ISSUE THREAD

**Issue by mhugo** [BRGM/gml_application_schema_toolbox#10]
The custom widget declared in import_gmlas_panel.ui cannot be found:

```
Traceback (most recent call last):
  File "/home/hme/src/QGIS/build/output/python/qgis/utils.py", line 338, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/hme/.qgis3/python/plugins/gml_application_schema_toolbox/__init__.py", line 35, in classFactory
    from .main import MainPlugin
  File "/home/hme/src/QGIS/build/output/python/qgis/utils.py", line 647, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/hme/.qgis3/python/plugins/gml_application_schema_toolbox/main.py", line 60, in 
    from .gui.dockwidget import DockWidget
  File "/home/hme/src/QGIS/build/output/python/qgis/utils.py", line 647, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/hme/.qgis3/python/plugins/gml_application_schema_toolbox/gui/dockwidget.py", line 27, in 
    from gml_application_schema_toolbox.gui.import_panel import ImportPanel
  File "/home/hme/src/QGIS/build/output/python/qgis/utils.py", line 647, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/hme/.qgis3/python/plugins/gml_application_schema_toolbox/gui/import_panel.py", line 10, in 
    from gml_application_schema_toolbox.gui.import_gmlas_panel import ImportGmlasPanel
  File "/home/hme/src/QGIS/build/output/python/qgis/utils.py", line 647, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/hme/.qgis3/python/plugins/gml_application_schema_toolbox/gui/import_gmlas_panel.py", line 50, in 
    os.path.dirname(__file__), '..', 'ui', 'import_gmlas_panel.ui'))
  File "/usr/lib/python3/dist-packages/PyQt5/uic/__init__.py", line 197, in loadUiType
    exec(code_string.getvalue(), ui_globals)
  File "", line 258, in 
  File "/home/hme/src/QGIS/build/output/python/qgis/utils.py", line 647, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ImportError: No module named 'qgsprojectionselectionwidget'
```

I tried to change the `<header>` element of import_gmlas_panel.ui, but without success.
@arnaud-morvan any idea ?

**Comment by mhugo** [comment]
Apprently, replacing qgsprojectionselectionwidget.h by qgis.gui seem to work
see afe18029f84e97

**Comment by arnaud-morvan** [comment]
Jusqu'ici j'avais aussi remplacé

<header>qgsprojectionselectionwidget.h</header>
par
<header>qgis.gui</header>

dans les fichiers ui, et ca passait.
Mais QtDesigner me fait le remplacement inverse à chaque enregistrement (un peu chiant à conserver du coup).

Lors de l'installation de QGIS il installe ce fichier :

https://github.com/qgis/QGIS/blob/master/python/custom_widgets/qgis_customwidgets.py
dans :
``/usr/lib/python3/dist-packages/PyQt5/uic/widget-plugins/qgis_customwidgets.py``

Il est possible que ce fichier ne s'installe pas, ou pas au bon endroit avec la compilation manuelle.

Ce fichier est un plugin pout QtDesigner, et il est utilisé pour interpréter correctement les fichier .ui avec des custom widgets QGIS.

Je pense que si tu copie ce fichier au bon endroit, tu ne devrais plus avoir de soucis.

**Comment by mhugo** [comment]
Ok, merci pour l'information !
