### ISSUE TITLE
Problem with /vsicurl_streaming url

### ISSUE THREAD

**Issue by mhugo** [BRGM/gml_application_schema_toolbox#11]
In "convert" tab, GMLAS import of the following url:
http://ressource.brgm-rec.fr/data/Piezometre/00463X0036/H1.2

It gives "Cannot open /vsicurl_streaming/http://ressource.brgm-rec.fr/data/Piezometre/00463X0036/H1.2"

However, with ogrinfo it works well:
```
ogrinfo -ro -al "GMLAS:/vsicurl_streaming/http://ressource.brgm-rec.fr/data/Piezometre/00463X0036/H1.2"
```

And in a python3 console:
```python
from osgeo import gdal
gdal.OpenEx("GMLAS:/vsicurl_streaming/http://ressource.brgm-rec.fr/data/Piezometre/00463X0036/H1.2")
```

However in the Python console of QGIS
```python
gdal.OpenEx("GMLAS:/vsicurl_streaming/http://ressource.brgm-rec.fr/data/Piezometre/00463X0036/H1.2")
Traceback (most recent call last):
  File "/usr/lib/python3.5/code.py", line 91, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/osgeo/gdal.py", line 2995, in OpenEx
    return _gdal.OpenEx(*args, **kwargs)
RuntimeError: Cannot open /vsicurl_streaming/http://ressource.brgm-rec.fr/data/Piezometre/00463X0036/H1.2
```

@arnaud-morvan any idea ?

**Comment by arnaud-morvan** [comment]
No idea, maybe @rouault could help you.

**Comment by rouault** [comment]
No idea. What if you set CPL_DEBUG=ON as environment variable ?

But it doesn't seem a good idea, performance-wise, to use /vsicurl_streaming/ with the GMLAS driver since the GMLAS driver may have to read the file several times due to the reading passes (e.g if using the REMOVE_UNUSED_.... options). Downloading it locally would probably be better.

**Comment by mhugo** [comment]
@rouault thanks, I will test without /vsicurl_streaming.
Here are some more informations with CPL_DEBUG=ON

```
Warning 1: CPL: Parsing /usr/local/share/gdal/gmlasconf.xsd
Warning 1: libXML: /tmp/gmlasconf_jgmtkqdv.xml:7: Element 'SchemaAnalysisOptions': This element is not expected. Expected is one of ( Validation, ExposeMetadataLayers, LayerBuildingRules, XLinkResolution, IgnoredXPaths, WriterConfig ).
GMLAS: XSD cache directory: /home/hme/.gdal/gmlas_xsd_cache
VSICURL: Start download for http://ressource.brgm-rec.fr/data/Piezometre/00463X0036/H1.2
VSICURL: Stop download for http://ressource.brgm-rec.fr/data/Piezometre/00463X0036/H1.2
OGR: XMLPlatformUtils::Terminate()
```

[gmlasconf_jgmtkqdv.xml.txt](https://github.com/BRGM/gml_application_schema_toolbox/files/867211/gmlasconf_jgmtkqdv.xml.txt)
[gmlasconf.xsd.txt](https://github.com/BRGM/gml_application_schema_toolbox/files/867212/gmlasconf.xsd.txt)

**Comment by mhugo** [comment]
Same error without /vsicurl_streaming ...

**Comment by mhugo** [comment]
Ok, apparently there are (at least) 2 problems:
- the generated gmlasconf.xml does not match the installed gdal xsd ...
- something in the handling of proxy parameters is wrong

**Comment by rouault** [comment]
The GDAL version must be out of date, since in its latest version gmlasconf.xsd has the SchemaAnalysisOptions element :
https://github.com/OSGeo/gdal/blob/trunk/gdal/data/gmlasconf.xsd

**Comment by sgrellet** [comment]
now that QGIS 3 built wih GDAL 2.2 is available from OsGeo4W, new feedback on this error

-- context
out of BRGM network (normally no proxy error)
QGIS build https://github.com/qgis/QGIS/commit/d55fa22
GDAL/OGR : 2.2.0

-- http://ressource.brgm-rec.fr/data/BoreholeView/BSS001REWW
=> 
RuntimeError: Cannot resolve https://forge.brgm.fr/svnrepository/epos/trunk/schemas/epos-lite.xsd 
Traceback (most recent call last):
  File "C:/Users/grellets/.qgis3/python/plugins\gml_application_schema_toolbox\gui\import_gmlas_panel.py", line 145, in on_validateButton_clicked
    self.validate()
  File "C:/Users/grellets/.qgis3/python/plugins\gml_application_schema_toolbox\gui\import_gmlas_panel.py", line 153, in validate
    data_source = self.gmlas_datasource()
  File "C:/Users/grellets/.qgis3/python/plugins\gml_application_schema_toolbox\gui\import_gmlas_panel.py", line 139, in gmlas_datasource
    open_options=openOptions)
RuntimeError: Cannot resolve https://forge.brgm.fr/svnrepository/epos/trunk/schemas/epos-lite.xsd

=> this error is already known: we faced it when parsing the flow with Java code (certificate declaration apparently).
But it shows that the XML flow is retrieved by the plugin and that GDAL tries to retrieves the underlying xsd

-- http://ressource.brgm-rec.fr/data/Piezometre/06988C0281/F.2
=> RuntimeError: Cannot open /vsicurl_streaming/http://ressource.brgm-rec.fr/data/Piezometre/06988C0281/F.2 
Traceback (most recent call last):
  File "C:/Users/grellets/.qgis3/python/plugins\gml_application_schema_toolbox\gui\import_gmlas_panel.py", line 145, in on_validateButton_clicked
    self.validate()
  File "C:/Users/grellets/.qgis3/python/plugins\gml_application_schema_toolbox\gui\import_gmlas_panel.py", line 153, in validate
    data_source = self.gmlas_datasource()
  File "C:/Users/grellets/.qgis3/python/plugins\gml_application_schema_toolbox\gui\import_gmlas_panel.py", line 139, in gmlas_datasource
    open_options=openOptions)
RuntimeError: Cannot open /vsicurl_streaming/http://ressource.brgm-rec.fr/data/Piezometre/06988C0281/F.2

-- http://ressource.brgm-rec.fr/data/DispositifCollecte/0000000073
RuntimeError: Cannot open /vsicurl_streaming/http://ressource.brgm-rec.fr/data/DispositifCollecte/0000000073 
Traceback (most recent call last):
  File "C:/Users/grellets/.qgis3/python/plugins\gml_application_schema_toolbox\gui\import_gmlas_panel.py", line 145, in on_validateButton_clicked
    self.validate()
  File "C:/Users/grellets/.qgis3/python/plugins\gml_application_schema_toolbox\gui\import_gmlas_panel.py", line 153, in validate
    data_source = self.gmlas_datasource()
  File "C:/Users/grellets/.qgis3/python/plugins\gml_application_schema_toolbox\gui\import_gmlas_panel.py", line 139, in gmlas_datasource
    open_options=openOptions)
RuntimeError: Cannot open /vsicurl_streaming/http://ressource.brgm-rec.fr/data/DispositifCollecte/0000000073

-- direct call to the WFS serveur behind 'http://ressource.brgm-rec.fr/data/DispositifCollecte/0000000073' to avoid potential influence of redirection by BRGM resolver (ex : HTTP 303). https://wfspoc.brgm-rec.fr/geoserver/ows?service=wfs&version=2.0.0&request=GetFeature&StoredQuery_ID=GetEnvironmentalMonitoringNetworkById&ID=DispositifCollecte.0000000073 

RuntimeError: Cannot open /vsicurl_streaming/https://wfspoc.brgm-rec.fr/geoserver/ows?service=wfs&version=2.0.0&request=GetFeature&StoredQuery_ID=GetEnvironmentalMonitoringNetworkById&ID=DispositifCollecte.0000000073 
Traceback (most recent call last):
  File "C:/Users/grellets/.qgis3/python/plugins\gml_application_schema_toolbox\gui\import_gmlas_panel.py", line 145, in on_validateButton_clicked
    self.validate()
  File "C:/Users/grellets/.qgis3/python/plugins\gml_application_schema_toolbox\gui\import_gmlas_panel.py", line 153, in validate
    data_source = self.gmlas_datasource()
  File "C:/Users/grellets/.qgis3/python/plugins\gml_application_schema_toolbox\gui\import_gmlas_panel.py", line 139, in gmlas_datasource
    open_options=openOptions)
RuntimeError: Cannot open /vsicurl_streaming/https://wfspoc.brgm-rec.fr/geoserver/ows?service=wfs&version=2.0.0&request=GetFeature&StoredQuery_ID=GetEnvironmentalMonitoringNetworkById&ID=DispositifCollecte.0000000073

**Comment by rouault** [comment]
what happens if you manually download
http://ressource.brgm-rec.fr/data/BoreholeView/BSS001REWW in a file called foo.xml and that in the OSGeo4W shell command line you execute :

ogrinfo -ro GMLAS:foo.xml

This works for me on Linux.

If that doesn't work in OSGeo4W, can you retry with

ogrinfo -ro --debug --config CPL_CURL_VERBOSE YES GMLAS:foo.xml 2> error_log.txt

and attach error_log.txt

**Comment by sgrellet** [comment]
GDAL 2.2.0, released 2017/04/28

D:\Temp>ogrinfo -ro GMLAS:foo.xml
ERROR 3: Cannot resolve https://forge.brgm.fr/svnrepository/epos/trunk/schemas/epos-lite.xsd
FAILURE: Unable to open datasource `GMLAS:foo.xml' with the following drivers.

and 

D:\Temp>ogrinfo -ro --debug --config CPL_CURL_VERBOSE YES GMLAS:foo.xml 2> error_log.txt
FAILURE: Unable to open datasource `CPL_CURL_VERBOSE' with the following drivers.

this one is not the ideal one for test as we know having the xsd behind our https://forge.brgm... already causes issues

[error_log.txt](https://github.com/BRGM/gml_application_schema_toolbox/files/1047017/error_log.txt)

**Comment by rouault** [comment]
@sgrellet Oops sorry I meant

ogrinfo -ro --debug on --config CPL_CURL_VERBOSE YES GMLAS:foo.xml 2> error_log.txt

('on' after --debug and not sure on windows If you need a space between 2> and error_log.txt)

**Comment by sgrellet** [comment]
see attached
I tried putting the xsd in gdal\gmlas_xsd_cache but does not change a thing. even when I tried applying your naming convention ->forge.brgm.fr_svnrepository_epos_trunk_schemas_epos-lite.xsd 
[error_log.txt](https://github.com/BRGM/gml_application_schema_toolbox/files/1047067/error_log.txt)

**Comment by rouault** [comment]
Interesting, I see "SSL certificate problem: self signed certificate in certificate chain"

Can your retry with :

ogrinfo -ro --debug on --config CPL_CURL_VERBOSE YES --config GDAL_HTTP_UNSAFESSL YES GMLAS:foo.xml 2> error_log.txt

**Comment by sgrellet** [comment]
successfull with 

with ogrinfo -ro --debug on --config CPL_CURL_VERBOSE YES --config GDAL_HTTP_UNSAFESSL YES GMLAS:foo.xml > stdout.txt 2>stderr.txt

[stderr.txt](https://github.com/BRGM/gml_application_schema_toolbox/files/1047107/stderr.txt)
[stdout.txt](https://github.com/BRGM/gml_application_schema_toolbox/files/1047108/stdout.txt)

**Comment by rouault** [comment]
OK, so if you define in your Windows user environment an environment variable ( https://www.nextofwindows.com/how-to-addedit-environment-variables-in-windows-7 ) GDAL_HTTP_UNSAFESSL=YES, log out, log in, remove the cached files, then that should work from the plugin as well.

@mhugo Do you think the plugin should have an option to do gdal.SetConfigOption('GDAL_HTTP_UNSAFESSL', 'YES') ? Or perhaps enable it by default.

**Comment by sgrellet** [comment]
works well 
http://ressource.brgm-rec.fr/data/BoreholeView/BSS001REWW -> spatialLite file created

'Load layer list' now works also with the 2 other URIs I reported in error above
http://ressource.brgm-rec.fr/data/Piezometre/06988C0281/F.2
http://ressource.brgm-rec.fr/data/DispositifCollecte/0000000073
Which is cool bu looks weird to me as those call INSPIRE xsd that are not behind httpS

the issue could be encountered by other people. I'd set it at YES by default with the possibility in the GUI to uncheck this.

**Comment by mhugo** [comment]
Hi, @sgrellet I've tried to load from the 3 addresses you gave, but cannot reproduce the problem. Have the certificates been updated ?

**Comment by sgrellet** [comment]
Good question. I don't know. but the 2 of addresses (Piezometer, DispositifCollecte) above make no use of https for the schema.

**Comment by sgrellet** [comment]
using the new import logic (see #22 ) on the 2 example file that are on the github
https://github.com/BRGM/gml_application_schema_toolbox/blob/master/samples/BRGM_raw_database_observation_waterml2_output.xml
https://github.com/BRGM/gml_application_schema_toolbox/blob/master/samples/BRGM_raw_database_observation_PointTimeseriesObservation_output.xml

I have RuntimeError: /vsicurl_streaming/http://schemas.opengis.net/swes/2.0/swesNotification.xsd:132:55 referenced element 'wsa:EndpointReference' not found. You may retry with the HANDLE_MULTIPLE_IMPORTS=YES open option
-> I can open the xsd and find that element in a browser.
with <HandleMultipleImports>true</HandleMultipleImports> in the gmlasconf file still the same issue

**Comment by mhugo** [comment]
vsicurl_stream problem reproduced but only under Windows with
http://ressource.brgm-rec.fr/data/Piezometre/06512X0037/STREMY.2

Fixed in https://github.com/BRGM/gml_application_schema_toolbox/commit/017c974b8971a7b4e2fc450730461dbd5795a3af

**Comment by mhugo** [comment]
During tests, I noticed a different behaviour after cleaning the local xsd cache (~/.gdal/gmlas_xsd_cache). @sgrellet can you try it ?

**Comment by mhugo** [comment]
... and the first was that GDAL_HTTP_UNSAFESSL was missing in "load layers"
Fixed in https://github.com/BRGM/gml_application_schema_toolbox/commit/efc05906ae947ccae27e7d11728dc676a8e8840a
