### ISSUE TITLE
Uncaught TypeError: __init__() got an unexpected keyword argument 'uri'


### ISSUE THREAD

**Issue by Guts** [BRGM/gml_application_schema_toolbox#126]
# Environment

- Plugin version: >= 1.3.0
- QGIS version:  3.16.4-Hannover Hannover, f1660f9da5 
- Operating System: Ubuntu 20.04
- Python version: 3.8 64 bits

# Description

## Steps to reproduce

Just open the wizard. 

The error message appears but doesn't not break anything.

## Logs

```python
Traceback (most recent call last):
  File "/home/jmo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/gml_application_schema_toolbox/gui/database_widget.py", line 111, in on_pgsqlConnectionsBox_currentIndexChanged
    self._pgsql_db = GmlasPostgisDB.from_name(
  File "/home/jmo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/gml_application_schema_toolbox/extlibs/qgis_processing_postgis.py", line 192, in from_name
    return cls(uri=uri)
TypeError: __init__() got an unexpected keyword argument 'uri'
```

**Comment by sgrellet** [comment]
Not reproduced under the following environment
Plugin version: 1.3.1
QGIS version: 3.16.2-Hannover Hannover, f1660f9da5
Operating System: Windows 10
Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)]

**Comment by towa** [comment]
This issue still occurs on 1.4.0beta4

```
TypeError: GmlasPostgisDB.__init__() got an unexpected keyword argument 'uri' 
Traceback (most recent call last):
  File "/home/t5n/.local/share/QGIS/QGIS3/profiles/HVBG/python/plugins/gml_application_schema_toolbox/gui/database_widget.py", line 111, in on_pgsqlConnectionsBox_currentIndexChanged
    self._pgsql_db = GmlasPostgisDB.from_name(
  File "/home/t5n/.local/share/QGIS/QGIS3/profiles/HVBG/python/plugins/gml_application_schema_toolbox/extlibs/qgis_processing_postgis.py", line 192, in from_name
    return cls(uri=uri)
TypeError: GmlasPostgisDB.__init__() got an unexpected keyword argument 'uri'


Python version: 3.10.4 (main, Mar 23 2022, 23:05:40) [GCC 11.2.0] 
QGIS version: 3.24.2-Tisler Tisler, exported 
```

Operating System: Arch Linux
