### ISSUE TITLE
V 1.3.0 - GMLAS Mode - Creating SQL file - 'DatabaseWidget' object has no attribute 'format' 

### ISSUE THREAD

**Issue by sgrellet** [BRGM/gml_application_schema_toolbox#129]
# Environment

- Plugin version: 1.3.0
- QGIS version:  3.16.2-Hannover Hannover, f1660f9da5 
- Operating System: Windows 10
- Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)]

# Description

- Relational mode (GMLAS) scenario - Local test scenario > step "1. initial information seed"
- following the steps but DON'T define a path & name to a specific file (this should create a 'Temporary file')
> AttributeError: 'DatabaseWidget' object has no attribute 'format' 

## To Reproduce

Follow https://brgm.github.io/gml_application_schema_toolbox/testing/scenario_mode_gmlas_local.html
Do step 1 as described

- all default options EXCEPT
- “Load layer list’ : click and keep both ‘boreholeview’ and ‘boreholeview_name’
- Target database > SQLite (write mode : Create)
- click on "Finish"
> Python error

## Expected behavior

- as described in the test scenario > "_Expected result : 1 new QGIS layer (boreholeview) and 1 table_"

# Additional context

- worked under V 1.2.1-beta1 : same environment

## Logs

```logs
AttributeError: 'DatabaseWidget' object has no attribute 'format' 
Traceback (most recent call last):
  File "C:/Users/grellets/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gml_application_schema_toolbox\gui\load_wizard.py", line 180, in validatePage
    self._panel.do_load()
  File "C:/Users/grellets/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gml_application_schema_toolbox\gui\import_gmlas_panel.py", line 315, in do_load
    if dest == "" and self.databaseWidget.format() == "SQLite":
AttributeError: 'DatabaseWidget' object has no attribute 'format'
```

**Comment by jgrocha** [comment]
Confirmed. I'm not able to export to SQLite.

Exporting to Postgresql is not working too.

```
2021-03-07T15:56:23     WARNING    Traceback (most recent call last):
              File "/home/jgr/.local/share/QGIS/QGIS3/profiles/biomedica/python/plugins/gml_application_schema_toolbox/gui/database_widget.py", line 111, in on_pgsqlConnectionsBox_currentIndexChanged
              self._pgsql_db = GmlasPostgisDB.from_name(
              File "/home/jgr/.local/share/QGIS/QGIS3/profiles/biomedica/python/plugins/gml_application_schema_toolbox/extlibs/qgis_processing_postgis.py", line 192, in from_name
              return cls(uri=uri)
             TypeError: __init__() got an unexpected keyword argument 'uri'
```

As far I was able to test, there is no way to export the data right now, since both the SQLite and PostgreSQl export are failing.

**Comment by sgrellet** [comment]
Works fine now with plugin version: 1.3.1
