### ISSUE TITLE
QGIS 3 pyspatialite problem

### ISSUE THREAD

**Issue by mhugo** [BRGM/gml_application_schema_toolbox#13]
Related issue on QGIS

https://issues.qgis.org/issues/16720

**Comment by mhugo** [comment]
The issue has been circumvented by relying on the ogr API with an output to GPKG in commit https://github.com/BRGM/gml_application_schema_toolbox/commit/6a1bad1539eb044ed0af1c70b3d411fb82df2133

**Comment by sgrellet** [comment]
Using plugin 1.1.0.zip
Importing the following URI (http://ressource.brgm-rec.fr/data/Piezometre/06512X0037/STREMY.2) using GMLAS triggers
1°/ this stack trace 
note that contrary to the message '20170711_EF.sqlite' is created and 
RuntimeError: SQLite driver failed to create D:/Temp/20170711_EF.sqlite and all the tables appear in the QGIs project
Traceback (most recent call last):
  File "C:/Users/grellets/.qgis3/python/plugins\gml_application_schema_toolbox\gui\import_gmlas_panel.py", line 280, in on_convertButton_clicked
    self.translate(self.import_params())
  File "C:/Users/grellets/.qgis3/python/plugins\gml_application_schema_toolbox\gui\gmlas_panel_mixin.py", line 65, in translate
    res = gdal.VectorTranslate(**params)
  File "C:\OSGEO4~1\apps\Python36\lib\site-packages\osgeo\gdal.py", line 718, in VectorTranslate
    return wrapper_GDALVectorTranslateDestName(destNameOrDestDS, srcDS, opts, callback, callback_data)
  File "C:\OSGEO4~1\apps\Python36\lib\site-packages\osgeo\gdal.py", line 3025, in wrapper_GDALVectorTranslateDestName
    return _gdal.wrapper_GDALVectorTranslateDestName(*args)
RuntimeError: SQLite driver failed to create D:/Temp/20170711_EF.sqlite

2°/ this error message when clicking on the point created using 'identify'
'Access violation - no RTTI data !'

**Comment by sgrellet** [comment]
I don't know if 100% related but part of the behaviour is the same
Importing that URI (https://forge.brgm.fr/svnrepository/epos/trunk/instances/BoreholeView.xml) in GMLAS triggers the stack trace below eventhough the sqlite file is created and the project loaded in the GUI (but I can't do nothing with the content).

Stack trace : 
  File "C:/Users/grellets/.qgis3/python/plugins\gml_application_schema_toolbox\gui\import_gmlas_panel.py", line 288, in on_convertButton_clicked
			    'postgres' if self.databaseWidget.format() == 'PostgreSQL' else 'spatialite')
			  File "C:/Users/grellets/.qgis3/python/plugins\gml_application_schema_toolbox\core\load_gmlas_in_qgis.py", line 79, in import_in_qgis
			    raise RuntimeError("SQL error")
			RuntimeError: SQL error

**Comment by mhugo** [comment]
Moved your issues to a new ticket #22. This one is closed
