### ISSUE TITLE
 __init__() got an unexpected keyword argument 'uri' 

### ISSUE THREAD

**Issue by sgrellet** [BRGM/gml_application_schema_toolbox#163]
# Environment

- Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
- QGIS version: 3.16.2-Hannover Hannover, f1660f9da5 
- Operating System: Windows

# Description

Bugs appearing (at least) through 2 UseCases:
- Just Launching the 'Load (wizard)'
- or step 3 of the "Relational mode (GMLAS) scenario - Local test scenario" when clicking on the  ‘Load’ button click

Note that in both cases the bug does not prevent to continue using the plugin

## To Reproduce

- Just Launching the 'Load (wizard)'
- or step 3 of the "Relational mode (GMLAS) scenario - Local test scenario" when clicking on the  ‘Load’ button click
- 

----

## Logs

```logs
TypeError: __init__() got an unexpected keyword argument 'uri' 
Traceback (most recent call last):
  File "C:/Users/grellets/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gml_application_schema_toolbox\gui\database_widget.py", line 111, in on_pgsqlConnectionsBox_currentIndexChanged
    self.pgsqlConnectionsBox.currentText()
  File "C:/Users/grellets/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gml_application_schema_toolbox\extlibs\qgis_processing_postgis.py", line 192, in from_name
    return cls(uri=uri)
TypeError: __init__() got an unexpected keyword argument 'uri'
```

**Comment by sgrellet** [comment]
Additionnal info: under a new profile with the exact same environment, the bug is not reproductible anymore
