### ISSUE TITLE
Create option is not working since the new db widget does not allow to create a new database

### ISSUE THREAD

**Issue by Guts** [BRGM/gml_application_schema_toolbox#197]
# Environment

- Plugin version: 1.4.0-beta4
- QGIS version: 3.16
- Operating System: ND

**Comment by sgrellet** [comment]
issue confirmed under QGIS 3.16.16

2022-02-03T14:47:38     WARNING    Traceback (most recent call last):
              File "C:\Users/grellets/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gml_application_schema_toolbox\gui\load_wizard.py", line 202, in validatePage
              self._panel.do_load()
              File "C:\Users/grellets/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gml_application_schema_toolbox\gui\import_gmlas_panel.py", line 404, in do_load
              import_in_qgis(
              File "C:\Users/grellets/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gml_application_schema_toolbox\core\load_gmlas_in_qgis.py", line 144, in import_in_qgis
              PlgLogger.log(message=f"DEBUG List of layers : {result}", log_level=4)
             UnboundLocalError: local variable 'result' referenced before assignment
