### ISSUE TITLE
AttributeError: module 'owslib' has no attribute 'wfs' when load layers from WFS connection

### ISSUE THREAD

**Issue by ismailsunni** [BRGM/gml_application_schema_toolbox#220]
# Environment

- Plugin version: 1.4.0-BETA4
- QGIS version: 3.24.3-Tisler
- Operating System: Ubuntu 20.04

# Description

<-- Here write a clear and concise description of what the bug is. -->

I got this python error like this:
```
An error has occurred while executing Python code: 

AttributeError: module 'owslib' has no attribute 'wfs' 
Traceback (most recent call last):
  File "/home/isunni/.local/share/QGIS/QGIS3/profiles/default/python/plugins/gml_application_schema_toolbox/gui/load_wizard_wfs.py", line 164, in on_connectBtn_clicked
    return self.on_connectBtn_clicked_()
  File "/home/isunni/.local/share/QGIS/QGIS3/profiles/default/python/plugins/gml_application_schema_toolbox/gui/load_wizard_wfs.py", line 167, in on_connectBtn_clicked_
    wfs = self.wfs()
  File "/home/isunni/.local/share/QGIS/QGIS3/profiles/default/python/plugins/gml_application_schema_toolbox/gui/load_wizard_wfs.py", line 148, in wfs
    return owslib.wfs.WebFeatureService(url=uri, version=version)
AttributeError: module 'owslib' has no attribute 'wfs'


Python version: 3.8.10 (default, Mar 15 2022, 12:22:08) [GCC 9.4.0] 
QGIS version: 3.24.3-Tisler Tisler, cf22b74e01 

Python Path:
/usr/share/qgis/python
/home/isunni/.local/share/QGIS/QGIS3/profiles/default/python
/home/isunni/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python38.zip
/usr/lib/python3.8
/usr/lib/python3.8/lib-dynload
/home/isunni/.local/lib/python3.8/site-packages
/usr/local/lib/python3.8/dist-packages
/usr/lib/python3/dist-packages
/home/isunni/.local/share/QGIS/QGIS3/profiles/default/python
/home/isunni/Documents/qgis/GSoC2019

```

## To Reproduce

1. Add WFS: https://www.gds.hessen.de/wfs2/boris/cgi-bin/brw/2020/wfs?VERSION=2.0.0 to QGIS
2. Open the Load Wizard
3. Choose WFS
4. Select the WFS connection above
5. Click Connect
6. Error thrown

## Expected behavior

It shouldn't give an error. I check with version 1.3.1, it can load the layers.

**Comment by ismailsunni** [comment]
Also occurs in Windows 10 with both QGIS 3.24 and 3.22.4 (LTR)
