### ISSUE TITLE
Error: Database Selection in GMLAS Wizard not working

### ISSUE THREAD

**Issue by towa** [BRGM/gml_application_schema_toolbox#237]
# Environment

- Plugin version: 233e51d014613c519006d704b3115418d5f65fd5
- QGIS version: 3.22 LTR
- Operating System: Windows 10

# Description

When trying to load a WFS in GMLAS mode the Database Selection in the Wizard is not working.

## spatialite
When selecting a spatialite connection and selecting finish in the Dialog the Dialog just stops. I think this is because of a broken if condition in the `ImportGmlasPanel.do_load()` function. The last else just returns, if none database formats match. My proposed solution would be to default to a temporary spatialite db (same with no connection selected)

## postgres
When selection a postgres connection I the Error shown below:
```
Traceback (most recent call last):
  File "C:\Users/User/AppData/Roaming/QGIS/QGIS3\profiles\HVBG/python/plugins\gml_application_schema_toolbox\gui\load_wizard.py", line 202, in validatePage
    self._panel.do_load()
  File "C:\Users/User/AppData/Roaming/QGIS/QGIS3\profiles\HVBG/python/plugins\gml_application_schema_toolbox\gui\import_gmlas_panel.py", line 407, in do_load
    import_in_qgis(
  File "C:\Users/User/AppData/Roaming/QGIS/QGIS3\profiles\HVBG/python/plugins\gml_application_schema_toolbox\core\load_gmlas_in_qgis.py", line 124, in import_in_qgis
    conn = md.createConnection(gmlas_uri, {})
AttributeError: 'NoneType' object has no attribute 'createConnection'
```

**Comment by towa** [comment]
PR #238 fixes the issue with spatialite.
I didn't manage to find a solution for the postgres error.
