### ISSUE TITLE
'NoneType' object has no attribute 'ExecuteSQL' when using 'gmlasconf-inspire.xml'

### ISSUE THREAD

**Issue by sgrellet** [BRGM/gml_application_schema_toolbox#25]
using V 1.1.1.zip
on 'http://ressource.brgm-rec.fr/data/Piezometre/06512X0037/STREMY.2'
with 'gmlasconf-inspire.xml' (note that I don't have this with 'gmlasconf.xml'
target : SQLITE

2017-07-13T16:52:55	1	Traceback (most recent call last):
			  File "C:/Users/grellets/.qgis3/python/plugins\gml_application_schema_toolbox\gui\import_gmlas_panel.py", line 308, in on_loadLayersBtn_clicked
			    import_in_qgis(source, self.databaseWidget.format(), schema)
			  File "C:/Users/grellets/.qgis3/python/plugins\gml_application_schema_toolbox\core\load_gmlas_in_qgis.py", line 61, in import_in_qgis
			    l = ds.ExecuteSQL(sql)
			AttributeError: 'NoneType' object has no attribute 'ExecuteSQL'

**Comment by mhugo** [comment]
Can't reproduce
