### ISSUE TITLE
GMLAS export issue

### ISSUE THREAD

**Issue by mhugo** [BRGM/gml_application_schema_toolbox#26]
When trying to export back a SQLite db to an XML (boreholeview):

```
Traceback (most recent call last):
  File "/home/hme/.qgis3/python/plugins/gml_application_schema_toolbox/gui/export_gmlas_panel.py", line 163, in on_exportButton_clicked
    self.translate(self.reproject_params(temp_datasource_path))
  File "/home/hme/.qgis3/python/plugins/gml_application_schema_toolbox/gui/gmlas_panel_mixin.py", line 65, in translate
    res = gdal.VectorTranslate(**params)
  File "/usr/local/lib/python3.5/dist-packages/osgeo/gdal.py", line 709, in VectorTranslate
    return wrapper_GDALVectorTranslateDestName(destNameOrDestDS, srcDS, opts, callback, callback_data)
  File "/usr/local/lib/python3.5/dist-packages/osgeo/gdal.py", line 3122, in wrapper_GDALVectorTranslateDestName
    return _gdal.wrapper_GDALVectorTranslateDestName(*args)
RuntimeError: Terminating translation prematurely after failed
translation of layer geom_cols_ref_sys (use -skipfailures to skip errors)
```

**Comment by mhugo** [comment]
It turns out the export feature has two steps: reprojection than conversion.
The reprojection process is https://github.com/BRGM/gml_application_schema_toolbox/commit/c1a1fe45e0990305cce76b4ca719ec2b8c9ceaff

**Comment by mhugo** [comment]
Oups
Added 'skipfailures' option
as well as OGR_SQLITE_SYNCRHONOUS=OFF in https://github.com/BRGM/gml_application_schema_toolbox/commit/c1a1fe45e0990305cce76b4ca719ec2b8c9ceaff
