### ISSUE TITLE
Download tab : getFeature not using the ows:HTTP from the GetCap

### ISSUE THREAD

**Issue by sgrellet** [BRGM/gml_application_schema_toolbox#47]
Using : 
https://www.emidius.eu/services/wfs?

The plugin calls 'https://www.emidius.eu/services/wfs?...' instead of 'http://www.emidius.eu/services/sheec/wfs' provided by the GetCaps

<ows:Operation name="GetFeature">
<ows:DCP>
<ows:HTTP>
<ows:Get xlink:href="http://www.emidius.eu/services/sheec/wfs"/>
<ows:Post xlink:href="http://www.emidius.eu/services/sheec/wfs"/>
</ows:HTTP>
</ows:DCP>

**Comment by sgrellet** [comment]
tried under v1.2.0-rc2
-> equests.exceptions.SSLError: HTTPSConnectionPool(host='www.emidius.eu', port=443): Max retries exceeded with url: /services/wfs?service=WFS&request=GetCapabilities&version=2.0.0 (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)'),)) 
Traceback (most recent call last):
  File "C:\OSGEO4~1\apps\Python36\lib\site-packages\urllib3\connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "C:\OSGEO4~1\apps\Python36\lib\site-packages\urllib3\connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "C:\OSGEO4~1\apps\Python36\lib\site-packages\urllib3\connectionpool.py", line 850, in _validate_conn
    conn.connect()
  File "C:\OSGEO4~1\apps\Python36\lib\site-packages\urllib3\connection.py", line 326, in connect
    ssl_context=context)
  File "C:\OSGEO4~1\apps\Python36\lib\site-packages\urllib3\util\ssl_.py", line 329, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\OSGEO4~1\apps\Python36\lib\ssl.py", line 401, in wrap_socket
    _context=self, _session=session)
  File "C:\OSGEO4~1\apps\Python36\lib\ssl.py", line 808, in __init__
    self.do_handshake()
  File "C:\OSGEO4~1\apps\Python36\lib\ssl.py", line 1061, in do_handshake
    self._sslobj.do_handshake()
  File "C:\OSGEO4~1\apps\Python36\lib\ssl.py", line 683, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)

During handling of the above exception, another exception occurred:...

Still with a browser it works (https://www.emidius.eu/services/europe/wfs?service=WFS&request=GetCapabilities&version=2.0.0). Is that a QGIS related bug or just that the server is 'banning' something related to the plugin ?
I can contact them if needed

**Comment by sgrellet** [comment]
cannot reproduce as the endpoint address got updated. 
changing tag & keeping issue for track record
