### ISSUE TITLE
GMLAS mode 1:N links

### ISSUE THREAD

**Issue by mhugo** [BRGM/gml_application_schema_toolbox#52]
Stacktrace generated.

Details to come

**Comment by sgrellet** [comment]
-> connected to https://wfspoc.brgm-rec.fr/geoserver/ows
-> choosing Feature type 'ef:EnvironmentalMonitoringFacility'
-> WFS Options Limit to 1 feature(s)
-> 'Download to': a temporary file or an explicit file path
-> then 'Load from WFS layer'
-> identify feature button on one of the points displayed 
1/N links tab generates the following Python error
'Une erreur est survenue lors de l'exécution du code suivant:
my_form_open( _qgis_featureform_48_48, _qgis_layer_environmenmonitoringfacility_legalbackground_legalbackground_3ae2fb09_7803_4723_9a8e_d072501fb0e1_48, _qgis_feature_20180122114002269)

Traceback (most recent call last):
  File "", line 1, in 
  File "", line 3, in my_form_open
  File "C:/Users/grellets/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gml_application_schema_toolbox\gui\qgis_form_custom_widget.py", line 72, in inject_custom_viewer_into_form
    xpath = no_ns(layer.customProperty("xpath", ""))
  File "C:/Users/grellets/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gml_application_schema_toolbox\core\xml_utils.py", line 36, in no_ns
    i=s.find(':')
AttributeError: 'NoneType' object has no attribute 'find''

Version de Python :
3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)]

Version de QGIS :
2.99.0-Master 'Master', b4be39f98b

**Comment by sgrellet** [comment]
Still on v1.2.0-rc2
Version de Python :
3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)]
Version de QGIS :
3.0.0-Girona 'Girona', 001c80b0c3

**Comment by sgrellet** [comment]
not testable on v1.2.0-rc2 because of #53

**Comment by sgrellet** [comment]
no more error raised using GMLAS toolbox plugin : v1.2.0-rc7
with http://ressource.brgm-rec.fr/data/Piezometre/06512X0037/STREMY.2

BUT still the content is not dynamically updated in form view in case you have an element that repeats itself (see ef:belongsTo and ef:hasObservation for that URI).

In tabular view ('basculer sur la vue tabulaire'), all the necessary info seems here (ex : networkfacility_pkid) but in form view ('basculer sur la vue formulaire'), when you chose one of the 8 elements for 'environmentalmonitoringfacility_belongsTo', nothing is updated on the right side (displayed 'Réseau patrimonial national de suivi quantitatif des eaux souterraines(RNESP)' and URI 'http://ressource.brgm-rec.fr/data/DispositifCollecte/0000000029"' and other remain displayed)

Version de Python : 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)]
Version de QGIS : 3.0.1-Girona Girona, a86bec25eb

**Comment by sgrellet** [comment]
one addition, still using http://ressource.brgm-rec.fr/data/Piezometre/06512X0037/STREMY.2
the following XPath does not seem to be handled properly in the GUI in form mode (/wfs:FeatureCollection/wfs:member/ef:EnvironmentalMonitoringFacility/ef:observingCapability/ef:ObservingCapability)
maybe it is due to the fact that we have a camelcase trick here (in the uml the association role and the featureType have the same name... which we can differentiate with camelCase writing).
In the GUI, in form mode, there is no content in environmmonitorifacility_observincapabili_observincapability corresponding to the XML snippet below whereas all is in table 'observingcapability1'

<ef:observingTime>
<gml:TimePeriod gml:id="ObservingCapability.TimePeriod.14636">...</gml:TimePeriod>
</ef:observingTime>
<ef:processType xlink:href="http://inspire.ec.europa.eu/codelist/ProcessTypeValue/process/" xlink:title="Process"/>
<ef:resultNature xlink:href="http://inspire.ec.europa.eu/codelist/ResultNatureValue/primary/" xlink:title="primary"/>
<ef:procedure/>
<ef:featureOfInterest xlink:href="http://ressource.brgm-rec.fr/data/EntiteHydroGeol/507AC00" xlink:title="Entite hydrogeologique 507AC00"/>
<ef:observedProperty xlink:href="http://ressource.brgm-rec.fr/data/somePath" xlink:title="GroundWaterLevel"/>

GMLAS toolbox plugin : v1.2.0-rc7
Version de Python : 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)]
Version de QGIS : 3.0.1-Girona Girona, a86bec25eb

**Comment by sgrellet** [comment]
Error reproduced in the same environment as above
Database properly created 
But same issue
-  the Form view content is not updated when you have 1..N links for example in environmentalmonitoringfacility_belongsto (though the good foreign keys are visible in Table Mode)

Test cases run
- loading the GMLAS Database that was attached to this issue (see 'Lead to the attached sqlLite DB : 20180417_EF_ST_REMY2.zip') via the 'Load a GMLAS database'
- also using this file https://github.com/BRGM/gml_application_schema_toolbox/blob/master/samples/BRGM_environmental_monitoring_facility_piezometer_1.xml.
Not the same feature instance but same data model as the URI used before is not used anymore (was a test environment)

Trying to ingest the same 'ST_REMY' data instance (same model) from the new URI generates another error -> will create the corresponding issue

**Comment by sgrellet** [comment]
Edit : there is actually no new error on the network side. It seems that our VPN tool was creating it. -> no new issue created (but still the former one is reproductible)
