### ISSUE TITLE
WFS version negotiation

### ISSUE THREAD

**Issue by mhugo** [BRGM/gml_application_schema_toolbox#60]
In the WFS connection dialog, when the users sets the WFS server to a bad one, the plugin should warn the user that it is not the actual version of the server.

Test the version upon the first connection and store a flag to tell if it is the actual version

**Comment by sgrellet** [comment]
tested on v1.2.0-rc2
when setted to a bad one (ex here V2.0 on a 1.1 WFS) the following stack trace is generated
AttributeError: 'NoneType' object has no attribute 'find' 
Traceback (most recent call last):
  File "C:/Users/grellets/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gml_application_schema_toolbox\gui\load_panel.py", line 130, in on_connectBtn_clicked
    wfs = self.wfs()
  File "C:/Users/grellets/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gml_application_schema_toolbox\gui\load_panel.py", line 104, in wfs
    return WebFeatureService(url=uri, version=version)
  File "C:\OSGEO4~1\apps\Python36\lib\site-packages\owslib\wfs.py", line 50, in WebFeatureService
    password=password)
  File "C:\OSGEO4~1\apps\Python36\lib\site-packages\owslib\feature\wfs200.py", line 65, in __new__
    username=username, password=password)
  File "C:\OSGEO4~1\apps\Python36\lib\site-packages\owslib\feature\wfs200.py", line 92, in __init__
    self._buildMetadata(parse_remote_metadata)
  File "C:\OSGEO4~1\apps\Python36\lib\site-packages\owslib\feature\wfs200.py", line 101, in _buildMetadata
    self.identification=ServiceIdentification(serviceidentelem)
  File "C:\OSGEO4~1\apps\Python36\lib\site-packages\owslib\ows.py", line 47, in __init__
    val = self._root.find(util.nspath('Title', namespace))
AttributeError: 'NoneType' object has no attribute 'find'
Version de Python : 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)] 
Version de QGIS : 3.0.0-Girona Girona, 001c80b0c3 

@mhugo : ticket closed, because the patch you committed will be implemented in a rc3 ?

**Comment by sgrellet** [comment]
tested ok on GMLAS toolbox plugin : v1.2.0-rc6
Python : 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)]
QGIS : 3.0.1-Girona Girona, a86bec25ebw
tested using
http://services.sandre.eaufrance.fr/geo/eth_FXX
