### ISSUE TITLE
WFS 'Connect' : Max retries exceeded

### ISSUE THREAD

**Issue by sgrellet** [BRGM/gml_application_schema_toolbox#61]
Specific issue because I now have that behaviour with 2 WFS endpoints
- https://www.emidius.eu/services/wfs?: see #47 
- and https://api.kuntatietopalvelu.fi/demo/wfs?service=wfs (to test #45)
-> urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.kuntatietopalvelu.fi', port=443): Max retries exceeded with url: /demo/wfs?service=WFS&request=GetCapabilities&version=1.1.0 (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)'),
In both cases, doing the getCaps in a browser works fine.

So something is related to QGIS or the Plugin.
Using
Version de Python : 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)] 
Version de QGIS : 3.0.0-Girona Girona, 001c80b0c3 
And GMLAS toolbox plugin v1.2.0-rc2

**Comment by sgrellet** [comment]
under v1.2.0-rc6
on  this endpoint (https://www.emidius.eu/services/europe/wfs?) - a slightly updated link from the above
- using add layer / WFS  : connexion to the WFS GetCapabilities works fine
- using GMLAS toolbox Wizard / WFS it crashes see below 
=> so the bug seems more related to the plugin itself

requests.exceptions.SSLError: HTTPSConnectionPool(host='www.emidius.eu', port=443): Max retries exceeded with url: /services/europe/wfs?service=WFS&request=GetCapabilities&version=2.0.0 (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)'),)) 

Traceback (most recent call last):
  File "C:\OSGEO4~1\apps\Python36\lib\site-packages\urllib3\connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "C:\OSGEO4~1\apps\Python36\lib\site-packages\urllib3\connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "C:\OSGEO4~1\apps\Python36\lib\site-packages\urllib3\connectionpool.py", line 850, in _validate_conn
    conn.connect()
  File "C:\OSGEO4~1\apps\Python36\lib\site-packages\urllib3\connection.py", line 326, in connect
    ssl_context=context)
  File "C:\OSGEO4~1\apps\Python36\lib\site-packages\urllib3\util\ssl_.py", line 329, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\OSGEO4~1\apps\Python36\lib\ssl.py", line 401, in wrap_socket
    _context=self, _session=session)
  File "C:\OSGEO4~1\apps\Python36\lib\ssl.py", line 808, in __init__
    self.do_handshake()
  File "C:\OSGEO4~1\apps\Python36\lib\ssl.py", line 1061, in do_handshake
    self._sslobj.do_handshake()
  File "C:\OSGEO4~1\apps\Python36\lib\ssl.py", line 683, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)
...

**Comment by mhugo** [comment]
I can't reproduce (tested under Linux)

**Comment by sgrellet** [comment]
Cannot reproduce anymore under
GMLAS toolbox plugin : v1.2.0-rc7
Version de Python : 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)]
Version de QGIS : 3.0.1-Girona Girona, a86bec25eb
Closing it
