### ISSUE TITLE
Support gml:boundedBy / Envelope in XML mode

### ISSUE THREAD

**Issue by sgrellet** [BRGM/gml_application_schema_toolbox#68]
split from #56 to differentiate issues in XML and relational mode
ko on v1.2.0-rc6 using the xml attached 

Traceback (most recent call last):
File "C:/Users/grellets/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gml_application_schema_toolbox\gui\load_wizard_xml.py", line 58, in validatePage
swap_xy=self.swapXYCheck.isChecked())
File "C:/Users/grellets/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gml_application_schema_toolbox\core\load_gml_as_xml.py", line 59, in load_as_xml_layer
return s.load_complex_gml(xml_uri, is_remote, attributes, geometry_mapping, logger, swap_xy)
File "C:/Users/grellets/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gml_application_schema_toolbox\core\load_gml_as_xml.py", line 327, in load_complex_gml
layer = self._create_layer('none', None, attr_list, src.title, "nogeom")
File "C:/Users/grellets/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gml_application_schema_toolbox\core\load_gml_as_xml.py", line 447, in _create_layer
layer = ds.CreateLayer("meta", geom_type = ogr.wkbNone)
AttributeError: 'NoneType' object has no attribute 'CreateLayer'

Python : 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)]
QGIS : 3.0.1-Girona Girona, a86bec25ebw
[ModelView_Envelope.zip](https://github.com/BRGM/gml_application_schema_toolbox/files/1919900/ModelView_Envelope.zip)

**Comment by mhugo** [comment]
I've tried to open ModelView_Envelope.xml, but can't see any geometry in it, am I missing something ?
What should we do with an Envelope but not geometries to show ?

**Comment by mhugo** [comment]
Sorry, I did not read apparently #56 :/ We thus need a polygon to be displayed for the BoundedBy element

**Comment by mhugo** [comment]
Fixed in https://github.com/BRGM/gml_application_schema_toolbox/commit/9b95f5be2dbdb976b83826e1fd49031b7280d029

**Comment by sgrellet** [comment]
ok under GMLAS toolbox plugin : v1.2.0-rc7
Version de Python : 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)]
Version de QGIS : 3.0.1-Girona Girona, a86bec25eb
