### ISSUE TITLE
GMLAS mode : dereferencing new features

### ISSUE THREAD

**Issue by sgrellet** [BRGM/gml_application_schema_toolbox#72]
GMLAS mode : dereferencing new features

Using GMLAS toolbox plugin : v1.2.0-rc7

1°/ https://forge.brgm.fr/svnrepository/epos/trunk/instances/BoreholeView.xml in GMLAS mode using the default conf
Then try to add various new features (object instance as opposed to dereferencing a codeList entry like http://inspire.ec.europa.eu/codelist/BoreholePurposeValue/hydrogeologicalSurvey)

2a°/ 'Load' on 'geologicaldescription _href' (http://ressource.brgm-rec.fr/obs/RawGeologicLogs/BSS001REWW)-> ok
"RuntimeError: Cannot determine the root layer 
Traceback (most recent call last):
  File "C:/Users/grellets/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gml_application_schema_toolbox\gui\qgis_form_custom_widget.py", line 140, in 
    btn.clicked.connect(lambda checked, dlg=dialog, l=layer, f=feature, fd=field_name: on_resolve_href(dlg, l, f, fd))
  File "C:/Users/grellets/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gml_application_schema_toolbox\gui\qgis_form_custom_widget.py", line 220, in on_resolve_href
    raise RuntimeError("Cannot determine the root layer")
RuntimeError: Cannot determine the root layer
"
but still tables are added 

2b°/ same with 'Load' on 'groundwaterlevel _href' (http://ressource.brgm-rec.fr/data/Piezometre/06512X0037/STREMY.2) -> ok
same error and the piezometer geometry gets properly added

other storyline that leads to the same issue
A°/ http://ressource.brgm-rec.fr/data/EntiteHydroGeol/507AC00  in GMLAS mode using the default conf (just set Swap coordinated to 'No')
Then try to add the aquifer system it pertains to
B°/ open 'gwaquifersystem' in form mode
C°/ 'Load' on href (http://ressource.brgm-rec.fr/data/EntiteHydroGeol/507AC) -> in GMLAS mode using the default conf (just set Swap coordinated to 'No')
same error and the aquifer geometry is properly added

Version de Python : 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)]
Version de QGIS : 3.0.1-Girona Girona, a86bec25eb

**Comment by sgrellet** [comment]
Tested under the following conf:
QGIS version: 3.0.1-Girona
QGIS code revision: a86bec25eb
Plugin 1.2.0

Both storyline end well. 
I confirm  the bug is closed
