### ISSUE TITLE
Problem with polish gml files in qgis 3.2.0 and 2.16.3

### ISSUE THREAD

**Issue by rwozniak93** [BRGM/gml_application_schema_toolbox#78]
Hi, 
I have problems with parsing gml files provided by polish authority. And now, I don't know if the problem is with plugin or with these gml files. 
So the problem is, when I try to load layer list in Load wizard (QGIS 3.2.0), I get an error:
`RuntimeError: /vsicurl_streaming/http://www.w3.org/1999/xlink.xsd:171:32 namespace 'http://www.w3.org/XML/1998/namespace' is referenced without import declaration 
Traceback (most recent call last):
  File "C:/Users/OEM/AppData/Roaming/QGIS/QGIS3\profiles\Rafik/python/plugins\gml_application_schema_toolbox\gui\import_gmlas_panel.py", line 156, in on_loadLayersButton_clicked
    self.validate()
  File "C:/Users/OEM/AppData/Roaming/QGIS/QGIS3\profiles\Rafik/python/plugins\gml_application_schema_toolbox\gui\import_gmlas_panel.py", line 164, in validate
    data_source = self.gmlas_datasource()
  File "C:/Users/OEM/AppData/Roaming/QGIS/QGIS3\profiles\Rafik/python/plugins\gml_application_schema_toolbox\gui\import_gmlas_panel.py", line 149, in gmlas_datasource
    open_options=openOptions)
  File "C:\PROGRA~1\QGIS 3.2\apps\Python36\lib\site-packages\osgeo\gdal.py", line 2918, in OpenEx
    return _gdal.OpenEx(*args, **kwargs)
RuntimeError: /vsicurl_streaming/http://www.w3.org/1999/xlink.xsd:171:32 namespace 'http://www.w3.org/XML/1998/namespace' is referenced without import declaration`

I've also tried to open this gml file in older version of your plugin, and then I've got the other error:
`Traceback (most recent call last):
			  File "C:/Users/OEM/.qgis2/python/plugins\gml_application_schema_toolbox\main.py", line 356, in onAddLayer
			    logger = MyLogger(self.p_widget))
			  File "C:/Users/OEM/.qgis2/python/plugins\gml_application_schema_toolbox\gml2relational\relational_model_builder.py", line 546, in load_gml_model
			    _populate(node, tables[root_name], None, tables_rows)
			  File "C:/Users/OEM/.qgis2/python/plugins\gml_application_schema_toolbox\gml2relational\relational_model_builder.py", line 428, in _populate
			    _populate(child, link.ref_table(), current_id, tables_rows)
			  File "C:/Users/OEM/.qgis2/python/plugins\gml_application_schema_toolbox\gml2relational\relational_model_builder.py", line 417, in _populate
			    child_id = _populate(child, link.ref_table(), current_id, tables_rows)
			  File "C:/Users/OEM/.qgis2/python/plugins\gml_application_schema_toolbox\gml2relational\relational_model_builder.py", line 428, in _populate
			    _populate(child, link.ref_table(), current_id, tables_rows)
			  File "C:/Users/OEM/.qgis2/python/plugins\gml_application_schema_toolbox\gml2relational\relational_model_builder.py", line 417, in _populate
			    child_id = _populate(child, link.ref_table(), current_id, tables_rows)
			  File "C:/Users/OEM/.qgis2/python/plugins\gml_application_schema_toolbox\gml2relational\relational_model_builder.py", line 360, in _populate
			    if len(node.attrib) == 0 and len(node) == 0 and node.text is None:
			AttributeError: 'list' object has no attribute 'attrib'`

I will be really grateful for any kind of help with this problem.

**Comment by sgrellet** [comment]
Thanks for your feedback.
Could you share a file or a reference to a webservice call ?

**Comment by sgrellet** [comment]
@rouault : I collected files from @rwozniak93 using d.gdrive.
the imported file is well formed and valid according to the xsd.
could you check what might go wrong ?

**Comment by rwozniak93** [comment]
Ok, so the soulution is just removing those include of EGB_OgolnyObiekt.xsd? I've tried it, and I have still the same error during parsing gml file. Or, maybe I'm doing something wrong - do you change gmlasconf.xml file or do you use default file? Maybe here is my problem

**Comment by rouault** [comment]
> Ok, so the soulution is just removing those include of EGB_OgolnyObiekt.xsd?

yes, make sure you do it in all other EGB_xxxx.xsd files

> do you change gmlasconf.xml file or do you use default file? 

Default one

**Comment by rwozniak93** [comment]
I'm a bit confused, but it still doesn't work. Do you have all .xsd files in the same directory, where you store gml file?

**Comment by rouault** [comment]
> Do you have all .xsd files in the same directory, where you store gml file?

Yes. Note that I test with GDAL 2.3.0 (not sure if there are really differences with GDAL 2.2.4 for that kind of issue)

**Comment by rwozniak93** [comment]
What more interesting, I've tried to open another gml file (one of these sample files from BRGM), and in QGIS 3.0.0 it didn't open, but in 2.16 it opened

**Comment by sgrellet** [comment]
Could you tell me which file you tried from BRGM so that I test here ?

**Comment by rwozniak93** [comment]
Yes, of course - BRGM_1GeolUnit_GeoSciML.xml

**Comment by rwozniak93** [comment]
Something magic - when I've opened the same file on the other machine, everything works :) so thanks for all your help

**Comment by sgrellet** [comment]
Great. Thanks for the update. I will close the issue then
