### ISSUE TITLE
Python error - download features

### ISSUE THREAD

**Issue by KoalaGeo** [BRGM/gml_application_schema_toolbox#82]
Hi,

Trying to use the plugin to access data from the Geological Survey of NWS - https://gs.geoscience.nsw.gov.au/geoserver/ows?Service=wfs&version=1.1.0&request=GetCapabilities 

Keep getting python errors

2019-04-01T11:26:13     WARNING    Traceback (most recent call last):
              File "C:/Users/edlew/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gml_application_schema_toolbox\gui\load_wizard_xml.py", line 36, in validatePage
              gml_path = self.wizard().gml_path()
              File "C:/Users/edlew/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gml_application_schema_toolbox\gui\load_wizard.py", line 181, in gml_path
              self._wfs_page.download(gml_path)
              File "C:/Users/edlew/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gml_application_schema_toolbox\gui\load_wizard_wfs.py", line 227, in download
              self.download_features(output_path)
              File "C:/Users/edlew/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gml_application_schema_toolbox\gui\load_wizard_wfs.py", line 255, in download_features
              params['bbox'] = self._get_bbox(wfs)
              File "C:/Users/edlew/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gml_application_schema_toolbox\gui\load_wizard_wfs.py", line 215, in _get_bbox
              assert default_crs.isValid()
             AssertionError
             
Any ideas? Or is it a bug? 

Cheers, 

Edd

**Comment by nmtoken** [comment]
The service is giving HTTP 503 issues at the moment, so it could be an issue at the server end. 

Did you try too with a WFS version 2.0.0 request also?
